package com.bookstore;

import com.bookstore.domain.Book;
import com.bookstore.repos.BookRepo;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;

@Controller
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private BookRepo bookRepo;

    @GetMapping("/greeting")
    public String greeting(@RequestParam(name="name", required=false, defaultValue="World") String name, Model model) {
        model.addAttribute("name", name);
        return "greeting";
    }

    @GetMapping("/")
    public String main(@RequestParam(name="name", required=false, defaultValue="World") String name, Model model) {
        Iterable<Book> books =  bookRepo.findAll();
        model.addAttribute("books", books);
        return "main";
    }

    @PostMapping
    public String addNewBook (
            @RequestParam String title,
            @RequestParam String author,
            @RequestParam Integer quantity,
            Model model) {
        // @RequestParam means it is a parameter from the GET or POST request

        Book book = new Book(title, author, quantity);
        bookRepo.save(book);

        Iterable<Book> books =  bookRepo.findAll();
        model.addAttribute("books", books);

        return "main";
    }
}